name = "Schule"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Schule"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
scope = "leanprover"
name = "doc-gen4"

[[lean_lib]]
name = "Schule"
